### ISSUE TITLE
"To run this application, you need to install .NET" when I already have it installed

### ISSUE THREAD

**Issue by sm4rd4** [dnmalenke/Calc2KeyCE#10]
So, this is really annoying me.
I'm trying to use the .exe version of Calc2Key because it's the only one that supports keymapping (to my knowledge), but whenever i try to run it, it keeps telling me "To run this application, you need to install .NET. Would you like to install it now?" And clicking "Yes" does nothing. 

The universal application works perfectly fine.

I reinstalled .NET version 5.0.17 and still no dice. Am I missing something here?

I'm running this on Windows 10, version 22H2.

**Comment by dnmalenke** [comment]
Make sure you're downloading the .NET Desktop Runtime
![image](https://github.com/dnmalenke/Calc2KeyCE/assets/21128448/2d195be9-620a-45fb-94ed-0297d354a141)
