### ISSUE TITLE
usbdrvce.8xv not found

### ISSUE THREAD

**Issue by Jeremy5909** [dnmalenke/Calc2KeyCE#2]
I can't find usbdrvce.8xv in the download?? Sorry im new to this... any help appreciated

**Comment by dnmalenke** [comment]
https://github.com/dnmalenke/Calc2KeyCE/releases/tag/v1.4.1

**Comment by Jeremy5909** [comment]
> https://github.com/dnmalenke/Calc2KeyCE/releases/tag/v1.4.1

Im dumb.... ty

**Comment by Jeremy5909** [comment]
> https://github.com/dnmalenke/Calc2KeyCE/releases/tag/v1.4.1

One last thing, I cant change the USB ID because its 0451E008 instead of 0451E009.. is this important?

**Comment by dnmalenke** [comment]
Yes, it is important, you need to create a new device using zadig

**Comment by Jeremy5909** [comment]
Sorry for all the questions.. how do i do that?

**Comment by Jeremy5909** [comment]
Oh nevermind, just Device > Create New Device? is that all and does it matter what i naem it or anything

**Comment by dnmalenke** [comment]
Easiest way would be to run calc2key on the calculator, then run zadig and it should open to the proper device IDs and you'll be able to install the driver from there

**Comment by Jeremy5909** [comment]
Tysm
