### ISSUE TITLE
computer dosn't reconise my calculator win10 21h2

### ISSUE THREAD

**Issue by nono17k** [dnmalenke/Calc2KeyCE#4]
my computer dos't reconise my calculator after i instaled the drivers from ziag ( neither ti connect or calctokey)

it also dosn't seem to be seen on the device manager

**Comment by dnmalenke** [comment]
The calculator may appear as Unknown Device #1 in device manager. If you can find it, please uninstaller the driver and delete the driver software if that is an option in device manager. 
TI Connect should now be able to detect the calculator.
If it does, run Calc2KeyCE on the calculator, then run Zadig and try again.

**Comment by nono17k** [comment]
it fixed after a reboot , thanks
