### ISSUE TITLE
USB ID Mismatch

### ISSUE THREAD

**Issue by NoozAbooz** [dnmalenke/Calc2KeyCE#8]
It seems like the majority of TI84+CEs have a USB ID of 0451:E008, however your program seems to be hardcoded to use :E009. My calculator isn't being detected by the program either, since it has the E008 ID.

**Comment by dnmalenke** [comment]
If you run the calc2keyce program on the calculator, it will change the USB pid to e009

**Comment by NoozAbooz** [comment]
> If you run the calc2keyce program on the calculator, it will change the USB pid to e009

Ah sorry, I didn't see that part. On a side note, when I try to run the program, it spits out a error. The calculator-side program is running, and the driver seems to be installed. 
![image](https://github.com/dnmalenke/Calc2KeyCE/assets/44128563/14a9fd4d-f451-4e0c-b89a-2593bdc7c064)
![image](https://github.com/dnmalenke/Calc2KeyCE/assets/44128563/801485b6-bbc8-4e90-8dec-45b3e91d9f8c)
